key_value_replace:
    - find_key: $.properties.parameters.greeting.defaultValue
      replace_value:
          prod: "hello from prod"
      item_type: "DataPipeline"
      item_name: "pl_demo"

    - find_key: $.properties.parameters.source_folder.defaultValue
      replace_value:
          prod: "raw/prod"
      item_type: "DataPipeline"
      item_name: "pl_demo"

    - find_key: $.properties.parameters.batch_size.defaultValue
      replace_value:
          prod: 5000
      item_type: "DataPipeline"
      item_name: "pl_demo"

    - find_key: $.properties.parameters.is_debug.defaultValue
      replace_value:
          prod: false
      item_type: "DataPipeline"
      item_name: "pl_demo"

    - find_key: $.properties.parameters.target_workspace_id.defaultValue
      replace_value:
          prod: "$workspace.$id"
      item_type: "DataPipeline"
      item_name: "pl_demo"

    - find_key: $.properties.activities[?(@.name=="Wait Before Run")].typeProperties.waitTimeInSeconds
      replace_value:
          prod: 10
      item_type: "DataPipeline"
      item_name: "pl_demo"

    - find_key: $.properties.parameters.tables.defaultValue
      replace_value:
          prod:
              - "dbo.customers"
              - "dbo.orders"
              - "dbo.invoices"
      item_type: "DataPipeline"
      item_name: "pl_process_tables"

    - find_key: $.properties.parameters.load_type.defaultValue
      replace_value:
          prod: "incremental"
      item_type: "DataPipeline"
      item_name: "pl_process_tables"

    - find_key: $.properties.parameters.wait_seconds_per_table.defaultValue
      replace_value:
          prod: 5
      item_type: "DataPipeline"
      item_name: "pl_process_tables"

    - find_key: $.properties.parameters.fail_on_empty.defaultValue
      replace_value:
          prod: false
      item_type: "DataPipeline"
      item_name: "pl_process_tables"
